### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Natnael-Alemayehu** [fatma316/AgrochainApp#1]
I am getting a BigNumber Error: new BigNumber() not a base 16 number error when I want tp get farmers credentials
![image](https://user-images.githubusercontent.com/61546827/149081998-b29cd69e-3e59-4aab-84ff-47c4651d429d.png)

**Comment by fatma316** [comment]
Hello, Actually it works for me … have u solved the issue ?    Chaabene Fatma  Software Engineering Student at   National Engineering School of Carthage   (+216) 53 771 130                  De : Natnael-AlemayehuEnvoyé le :mercredi 12 janvier 2022 08:22À : fatma316/AgrochainAppCc : SubscribedObjet :[fatma316/AgrochainApp] Bug (Issue #1) I am getting a BigNumber Error: new BigNumber() not a base 16 number error when I want tp get farmers credentials—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Natnael-Alemayehu** [comment]
I fixed it. Thank you for reaching out.
